marijnh/Postmodern

- cl-postgres.asd
- cl-postgres/tests.lisp
- postmodern.asd
- postmodern/tests.lisp
- simple-date.asd
- simple-date/tests.lisp
Eos is discontinued - good thing it's trivial to revert.
Tests for cl-postgres and postmodern should share the connection.
Also, test-op works just fine, so no need for this perform methods.
> Go back to 5am, modernize test systems

- cl-postgres.asd
- cl-postgres/interpret.lisp
- cl-postgres/package.lisp
- cl-postgres/protocol.lisp
- cl-postgres/simple-date-tests.lisp
- cl-postgres/tests.lisp
- simple-date/cl-postgres-glue.lisp
- simple-date/simple-date.lisp
So I think this is ready to go. I like the idea of the type-interpreter, rather than just a cons for the issue of whether to use binary, and possibly providing both a binary and a text reader. But, the big question I have is whether I should have avoided this altogether by adding the reader for type 2249 (row types) to my own readtable and left the whole issue to the application. Or we could provide some sort of *binary-row-sql-readtable* that folks could use. Lots of ways to solve the problem that are now more apparent to me, but what's here works. One open question is what's the default for row types? binary or text?
> Text and binary interpreter support

- cl-postgres/interpret.lisp
- cl-postgres/tests.lisp
- simple-date/cl-postgres-glue.lisp
- simple-date/simple-date.lisp
Default (non simple-date) support for the postgres time and timestamp-with-timezone types.
> add support for postgres time type

- cl-postgres/interpret.lisp
- cl-postgres/tests.lisp
I thought we were done with this, but there's another corner case I overlooked: an array of row types. In this case, we have to decide text/binary when we request the array value. Since the default for row types is text, we better default to text for arrays of rows as well.
* when we read a record array (row types), we need to decide ahead of
time if we want text or binary. In other words, we can't get a binary
array with text row types in it. Therefore, we'll respect the row
type text/binary choice and use that to decide of the record array
should come back as text or binary.
* add test for this while we're at it
> respect text/binary choice for record arrays

- cl-postgres/interpret.lisp
- cl-postgres/package.lisp
- cl-postgres/tests.lisp
These commits allow for:
1) removing the sql-reader for a given oid by passing NIL as the function argument to set-sql-reader
2) defining and exporting constants for time, timestamp, and timestamptz (timestamp with time zone) oids
3) tests for text reading of timestamps with time zones
If you like this interface, we can continue to define constants for the other oids that have (default) binary readers.
> Timestamp text reader

- s-sql/s-sql.lisp
Wrapping :@ keywords with || as cl-annot breakes the usage. This fix
should have no issues as:
(and
(eq  :|@@| :@@)
(eq  :|@>| :@>)
(eq  :|@<| :@<)
(eq  :|@| :@)) => t
> Avoid the conflict on cl-annot's macro character @.

- cl-postgres.asd
- postmodern.asd
- s-sql.asd
- simple-date.asd
Do NOT call OPERATE (via its alias OOS) from within PERFORM :AFTER methods.
Follow the recommended ASDF best practices.
https://gitlab.common-lisp.net/asdf/asdf/blob/master/doc/best_practices.md
Keep as comments the recommended way to establish system connections
(which itself is discouraged).
> Fix .asd files so they work well with ASDF 3.3

- postmodern/query.lisp
There is a bug in the "query" macro: if any of the args is a form that evaluates "query", the result will be incorrect. The reason is that the macro first calls "prepare-query" and then evaluates the arguments.
Another call to the query macro will destroy the prepared query, since "query" always uses the same name for the prepared statement (empty string).
> Fix bug in QUERY macro.

- postmodern/namespace.lisp
schema-exist-p is now deprecated but still available.
> Created schema-exists-p which is more consistent with naming scheme.

- cl-postgres/public.lisp
- postmodern/prepare.lisp
- s-sql/tests.lisp
This changes the meta-information hash to use strings instead of keywords, thus eliminating a source of heap exhaustion. See Issue 110.
It also corrects a few typos in the s-sql/tests.lisp test on the new create-table-full function.
> fixes issue 110 on heap exhaustion and corrects a typo in s-sql/tests.lisp

- cl-postgres/sql-string.lisp
For write-rational-as-floating-point and write-ratio-as-floating point.
> Attribution for code contribution to Attila Lendvai

- cl-postgres/sql-string.lisp
- cl-postgres/tests.lisp
- postmodern.asd
- postmodern/package.lisp
- postmodern/transaction.lisp
- postmodern/util.lisp
- s-sql/s-sql.lisp
Also corrects typos in write-rational-as-floating-point, write-ratio-as-floating-point.
Still need to write up documentation for the beginning of isolation level support
> Initial framework for adding isolation level support to transactions

- ROADMAP.md
- doc/isolation-notes.html
- doc/isolation-notes.org
- doc/postmodern.html
- doc/postmodern.org
- doc/s-sql.org
- postmodern.asd
- postmodern/package.lisp
- postmodern/tests/test-dao.lisp
- postmodern/tests/tests.lisp
- postmodern/transaction.lisp
- s-sql/s-sql.lisp
- s-sql/tests/tests.lisp
Isolation level functionality now directly in with-transaction and with-logical transaction macros. This is a substantial change from the previous implementation attempt that was reverted last week.
Also added the ability to truncate tables (delete all rows).
Dao tests have been separated into a separate file in preparation for more testing and functionality.
> With-transaction and with-logical-transaction can now specify isolation levels

- postmodern.asd
- s-sql/s-sql.lisp
A utility function to split-fully qualified table names requires split-sequence. Adding the dependency fixes the build failures.
Also def-sql-op now generates findable docstrings. Previously the docstring was getting generated outside the generated method.
> Adding a dependency on split-sequence and def-sql-op now generates findable doc-strings

- s-sql.asd
- s-sql/s-sql.lisp
Checking if is more the CAR of the body is a documentation
string is not enough to determine if we are looking at a docstring. If
the string is the only element of the body then it is part of the method
body. Leverage ALEXANDRIA:PARSE-BODY to extract the documentation string and
any declarations in DEF-SQL-OP.
Another defect on DEF-SQL-OP's implementation is the Unwanted variable
capture of OP. Gensym it.
Although I'm adding a new dependency, ALEXANDRIA, I don't think is an issue as it is ubiquitous in the CL ecosystem.
> DEF-SQL-OP: Use Alexandria's parse-body

- s-sql/s-sql.lisp
Genera's macro reader does not seem to intern symbols beginning with # if in string form. Surround the symbol with |...| instead.
> Use symbol format for sql operators

- doc/postmodern.html
- doc/postmodern.org
- postmodern/package.lisp
- postmodern/prepare.lisp
- postmodern/tests/tests.lisp
Allow some auto overwriting of prepared statements
When the exported postmodern parameter *allow-overwriting-prepared-statements*
is set to t (the default), prepared statements created with defprepared
will overwrite existing prepared statements of the same name
if the query statement provided to defprepared is different than the query
statement which exists in the postmodern meta connection hashtable. Remember
the prepared statements are stored separately for each postgresql
session. When set to nil, existing prepared statements with the
same name will not be overwritten regardless of whether the statements
are the same.
Making the check only at the postmodern meta connection
level avoids hitting the database again, but there is always
a possibility that postmodern and postgresql can get …
> Allow some auto overwriting of prepared statements

- postmodern/table.lisp
- postmodern/tests/test-dao.lisp
Without this fix, `INSERT-DAO` would signals an error since the SQL INSERT statement tries to return a column that does not exist.
> Fix INSERT-DAO for slots with a different column name

- cl-postgres/protocol.lisp
cl-postgres function read-byte-delimited was calling
(read-simple-str socket) instead of (read-str socket). This
drops characters when the socket is actually providing utf8
characters in non-Latin1 encodings.
Changed to (read-str socket).
> Fixed warnings in non-Latin1 encodings

- LICENSE
- postmodern.asd
- postmodern/execute-file.lisp
- postmodern/package.lisp
This copies https://github.com/dimitri/pgloader/blob/master/src/utils/read-sql-files.lisp into Postmodern.
TODO: tests.
Limitation: the SQL file in question cannot contain `BEGIN` or `COMMIT` since each statement is executed inside a transaction.
> Port execute-file from pgloader

- cl-postgres.asd
- cl-postgres/tests/simple-date-tests.lisp
- cl-postgres/tests/test-package.lisp
- s-sql.asd
package cl-postgres-simple-date-tests needs to kept separate. Some people use simple-date, some people use local-time. the Sept 14 commit to solve Genera compilation issues pulled cl-postgres-simple-date-tests into the main tests, triggering package-does-not-exist errors. This should resolve that problem. 
Symbolics - you will need to validate that this does not create any new Genera problems.
> fix compiling errors created by September 14 commit

- postmodern/table.lisp
It's easy to cause infinite loop by passing non-dao object to #'dao-keys
> Trigger clear error instead of infinite loop 

- postmodern/table.lisp
Is there a reason prepared stmt were not used here?
> Prepare statement for insert-dao

- doc/postmodern.html
- doc/postmodern.org
- doc/s-sql.org
- postmodern/execute-file.lisp
- postmodern/package.lisp
- postmodern/table.lisp
- postmodern/tests/test-dao.lisp
- postmodern/util.lisp
- s-sql/tests/test-arrays.lisp
- s-sql/tests/tests.lisp
Read-queries was broken and not correctly reading files of sql statements. Now fixed.
Posgresql version 12 seems to have a small calculation difference form version 11 in some of the aggregation functions. The unit tests have been slightly rounded to account for those differences.
Documentation has been updated. 
Some utility functions were added:
list-roles
cache-hit-ratio
bloat-measurement
unused-indexes
check-query-performance
Note that check-query-performance requires that the postgresql
extension pg_stat_statements be available and your postgresql
config file must have shared_preload_libraries = 'pg_stat_statements'
list-roles returns a list of alists of rolenames, role attributes and membership in roles.
See https://www.postgresql.org/docs/current/role-membership.html for an …
> Fix broken read-queries and some test results

- cl-postgres.asd
- cl-postgres/package.lisp
- cl-postgres/public.lisp
- doc/cl-postgres.org
Adds get-postgresql-version to cl-postgres
An exported function providing syntactic sugar to easily get the version of the connected postgresql
instance as a float.
For the curious, other postgresql data is available from the database
connection in a hashtable accessible with the accessor
connection-parameters. As of version 12 the following parameters were
provided:
"secret_key"
"pid"
"TimeZone"
"standard_conforming_strings"
"session_authorization"
"server_version"
"server_encoding"
"is_superuser"
"IntervalStyle"
"integer_datetimes"
"DateStyel"
"client-encoding"
"application_name"
> Adds get-postgresql-version to cl-postgres

- cl-postgres/public.lisp
As pointed out, postgresql versions pre version 10 could have three
levels of version numbers. get-postgresql-version now returns the version string.
> get-postgresql-version modified to return version string

- postmodern/connect.lisp
- postmodern/namespace.lisp
- postmodern/tests/tests.lisp
If reconnect happens inside (with-schema...) postmodern will reconnect
with the schema set inside the with-schema scope.
> Resolve issue 186. Reconnect to saved schema path

- s-sql/s-sql.lisp
Lock on package COMMON-LISP violated when defining REAL as a type specifier while in package S-SQL
Revert change that created the issue. Will look at phoe's suggestion as soon as possible.
> fix deftype real breakage

- cl-postgres/protocol.lisp
Affected by this while experimenting with notify/listen.
Currently, `get-notification` always fails with
```
error in FORMAT: Unknown directive (character: Space)
```
Used to be trailing tilde, which is valid, before
9662cb493b7a4bef43dc0663d452811d303514c4; reverting back to that.
> Fix get-notification format-control string

- cl-postgres/interpret.lisp
Replace lambdas in set-sql-datetime-readers with full functions to better facilitate temporary reader swapping.
> Split default datetime readers

- doc/create-tables.html
- doc/create-tables.org
The doc examples were missing the critical t value parameter
> Correct typo in docs using generated-as-identity

- cl-postgres.asd
- doc/postmodern.org
- postmodern.asd
- postmodern/package.lisp
- postmodern/prepare.lisp
- postmodern/table.lisp
- postmodern/tests/test-dao.lisp
- postmodern/tests/tests.lisp
- postmodern/transaction.lisp
- postmodern/util.lisp
- s-sql.asd
- s-sql/tests/tests.lisp
251 - lispworks added to depends-on usockets in cl-postgres
250 - dao-insert reverts back to using a query rather than preparing a statement on every insert
Prepare statements in postgresql only save resources for complex queries. Since postmodern's daos are very simple, prepared statements do not generate the benefit they might in other cases. The prepared statements as written were also creating statement identification conflicts when daos having unbound slots were inserted. The use of prepared statements in this situation was added in 2019 and is now being reverted. Many more tests have been added to testing the dao-code and hopefully we will keep this cleaner from now on.
> Resolve Issues 250 and 251

- cl-postgres/protocol.lisp
- cl-postgres/public.lisp
Hello,
I found that most database providers gives self-signed certificates, which fails under current default configuration.
I had to add this flag to make it work for my current project, please let me know if the changes are relevant or  I should add something else.
Thank you,
> Added flag to avoid SSL certificate verification.

- cl-postgres.asd
- doc/s-sql.html
- doc/s-sql.org
- postmodern.asd
- s-sql.asd
- s-sql/s-sql.lisp
- s-sql/tests/tests.lisp
s-sql operators :insert-into and :insert-rows-into get added capabilities
Previously :insert-into (but not :insert-rows-into) had some limited capability for dealing with duplicates when inserting new data. Specifically, both can now use all the possibilities provided by Postgresql up to version 13:
- overriding-system-value
- overriding-user-value
- on-conflict-do-nothing
- on-conflict
- on-conflict-on-constraint
- on-conflict-update
- do-nothing
- update-set
- from
- where
- returning
See updated s-sql docs for examples. See also extensive examples in the file s-sql/tests/tests.lisp
> Add more upsert capability to s-sql operators

- CHANGELOG.md
- ROADMAP.md
- cl-postgres/protocol.lisp
- doc/postmodern.html
- doc/postmodern.org
- postmodern.asd
- postmodern/package.lisp
- postmodern/roles.lisp
- postmodern/tests/test-dao.lisp
- postmodern/tests/test-roles.lisp
- postmodern/tests/test-table-info.lisp
- postmodern/tests/test-transactions.lisp
- postmodern/tests/tests.lisp
- postmodern/util.lisp
- s-sql/tests/test-intervals.lisp
- s-sql/tests/tests.lisp
Adds new utility functions
- table-description-menu which allows you to pick and choose
what table characteristics you want returned. See giant docstring for details.
- get-schema-comment which takes a schema name and returns the schema comment
as a string
- list-check-constraints which takes a fully qualified table name and returns
a list of lists of check constraints where each sublist has the form
of (check-constraint-name check).
Example: (list-check-constraints "s2.employees")
(("employees_birth_date_check" "CHECK (birth_date > '1900-01-01'::date)")
("employees_check" "CHECK (start_date > birth_date)")
("employees_salary_check" "CHECK (salary > 0::numeric)"))
Now exports
get-column-comments (the parameter string has changed if you were using the internal version) …
> Bugfix on ssl :try and new utility functions

- doc/cl-postgres.html
- doc/cl-postgres.org
- doc/postmodern.html
- doc/postmodern.org
Trying to put hyphens in database names will cause problems. Examples in the docs were confusing in this respect, so this is just trying to reduce confusion in the docs. No code changes made.
> Just clearing up some confusion in the docs

- cl-postgres/protocol.lisp
- cl-postgres/public.lisp
Microsoft Azure's Single Instance Postgresql gateway does not properly handle Postgresql connections when the application name is an empty string. We now use "postmodern-default" as the application name if the user has not specified anything else. I have been told that Azure's "flexible PG server" gateway did not have this problem.
Sidenote: The test suite was run calling a Postgresql database running on an Azure server instance 8,000 km away from the location of the server running the Postmodern code. Yes, the speed of light did make the test responses slower.
> Fix for Azure Single Instance connections

- cl-postgres.asd
- cl-postgres/tests/tests-saslprep.lisp
- doc/postmodern.html
- doc/postmodern.org
- postmodern.asd
- postmodern/execute-file.lisp
- postmodern/tests/sub1/tef-4.sql
- postmodern/tests/sub1/tef-5.sql
- postmodern/tests/sub1/tef-7.sql
- postmodern/tests/tef-1.sql
- postmodern/tests/tef-2.sql
- postmodern/tests/tef-3.sql
- postmodern/tests/tef-6.sql
- postmodern/tests/test-execute-file.lisp
- postmodern/tests/test-execute-file.sql
- postmodern/tests/test-fail-include-execute-file.sql
- postmodern/util.lisp
The execute-file function reads files of sql commands (which may include pulling 
in other files). Certain characters or combination of characters in sql comments 
would cause execute-file to fail. This commit fixes that and provides additional 
flexibility and safeguards.
Execute-file now by default removes single and multi-line comments from
sql files first before trying to parse them. This behavior can be changed
by passing nil as the new remove-comments optional parameter to execute-file.
The existing parsing code which looks at the sql commands themselves is 
untouched with this commit.
This commit adds \include and \include_relative and follows the
Postgresql practice that \i (and \include) and \ir (and
\include_relative) resolve differently.
Specifically \i or  \include which look …
> Fixes a bug in the execute-file function

- cl-postgres/config.lisp
- cl-postgres/package.lisp
- cl-postgres/protocol.lisp
- doc/cl-postgres.html
- doc/cl-postgres.org
Postgresql discovered a potential security issue in its server and standard driver which might allow a potential man-in-the-middle attack while attempting to make an ssl connection. See
[https://www.postgresql.org/about/news/postgresql-141-135-129-1114-1019-and-9624-released-2349/](https://www.postgresql.org/about/news/postgresql-141-135-129-1114-1019-and-9624-released-2349/)
for more details. Whilst Postmodern does not have this issue, after discussions  with the Postgresql security team, we agreed to flag evidence of attempted attacks using this vector.
If Postmodern is trying to set up an ssl connection and unexpected extra data was received prior to an ssl connection being created, such unexpected extra data may indicate an attempted man-in-the-middle attack. With this commit, in such …
> Flagging potential man-in-the-middle attack

- postmodern/package.lisp
- postmodern/transaction.lisp
This commit allows restarting transactions directly from the call-with-transaction call. Not safe for mutable code, obviously.
> Added retry-transaction restart in the call-with-transaction function.

- CHANGELOG.md
- cl-postgres.asd
- doc/postmodern.html
- doc/postmodern.org
- postmodern.asd
- postmodern/execute-file.lisp
- s-sql.asd
The warning should refer to Postmodern, not whatever the current package is.
Minor orgmode custom-id changes
> Fix bug in a warning in execute-file that referred to the current package

- cl-postgres/messages.lisp
We should remove (safety 0) here.  With sbcl 2.2.7, we get ....
```
CORRUPTION WARNING in SBCL pid 17 tid 17:
Memory fault at (nil) (pc=0x54100a44 [code 0x54100750+0x2F4 ID 0xc530], fp=0x7facf1b374d0, sp=0x7facf1b374a0) tid 17
The integrity of this image is possibly compromised.
Exiting.
0: fp=0x7facf1b374d0 pc=0x54100a44 CL-POSTGRES::PARSE-MESSAGE-BINARY-PARAMETERS
1: fp=0x7facf1b375c0 pc=0x541163e9 CL-POSTGRES::SEND-PARSE
2: fp=0x7facf1b376f8 pc=0x541230c5 (SB-PCL::FAST-METHOD DBI.DRIVER::PING (DBD.POSTGRES::<DBD-POSTGRES-CONNECTION>))
3: fp=0x7facf1b37790 pc=0x53a6f194 DBI::CONNECT-CACHED
4: fp=0x7facf1b37838 pc=0x53adc8bb (SB-PCL::FAST-METHOD INITIALIZE-INSTANCE :AFTER (RLGL.DB::DB/POSTGRESQL))
5: fp=0x7facf1b37880 pc=0x540eb8a9 (LAMBDA (SB-PCL::.P0. SB-PCL::.P1. SB-PCL::.P2. …
```
> Remove (safety 0)

- CHANGELOG.md
- README.md
- cl-postgres.asd
- cl-postgres/package.lisp
- cl-postgres/protocol.lisp
- doc/cl-postgres.html
- doc/cl-postgres.org
- doc/index.html
- doc/index.org
- doc/postmodern.html
- doc/postmodern.org
- doc/s-sql.html
- doc/s-sql.org
- postmodern.asd
- postmodern/tests/test-roles.lisp
- postmodern/util.lisp
- s-sql.asd
- s-sql/tests/test-intervals.lisp
- s-sql/tests/tests.lisp
Discontinue support for versions of sbcl < 1.2.5 which were compiled without support for bsd-sockets. I do not think anyone (even in the BSD crowd) is running on sbcl that old.
Drop unwarrented assumption that the role 'postgres' will always exist when dropping a role resulting in ownership changes of postgresql objects. 
Add more documentation on the limitation in s-sql on using lists in a parameterized statement. If you are trying to use a list in a parametized statement, you can't. You have to convert the list to a vector and use "any" rather than "in."
Add additional support for ssl connections to allow use of a root certificate for validation. Set \*ssl-root-ca-file* to the pathname for the root certificate.
> Minor fixes and clarifications

- doc/postmodern.html
- doc/postmodern.org
- postmodern/roles.lisp
In order to drop a role, you need to reassign ownership of any database objects it might own. The drop-role function takes an optional second parameter specifying where to reassign ownership. If that parameter is not provided, normal practice has been to reassign ownership to the default base role 'postgres'.
Some cloud setups do not give access to the 'postgres' role or it has been removed, so it cannot be used for this purpose. This change will assign the ownership rights to the role calling the drop-role function if the value of the new-owner parameter does not actually exist as a role.
> Minor enhancement for drop-role if role postgres does not exist

- postmodern/tests/test-roles.lisp
Running tests would delete other databases not included in tests.
> Fix critical bug in test-roles

- simple-date.asd
cl-postgres/simple-date-tests and simple-date/postgres-glue were failing to load due to missing new dependency on s-sql. Now fixed.
> Fix bug 315

- s-sql/s-sql.lisp
This commit changes s-sql::to-s-sql-string
to call cl-postgres:to-sql-string for unknown types, picking up other packages providing new methods for cl-postgres:to-sql-string.
> Fix for other packages methods for cl-postgres:to-sql-string

- postmodern/table.lisp
The column import functions were not being called inside do-select-dao
> Added missing import functions to do-select-dao macro.

- s-sql/s-sql.lisp
Adds [cube operators](https://www.postgresql.org/docs/current/cube.html#CUBE-OPERATORS-TABLE) (re: item 5 from #327)
Tested with SBCL 2.3.10 on Mac
> Add cube operators

- s-sql/tests/test-tables.lisp
Now the compilation of the test suite works again.
Still many tests do not succeed.
> Fix: add missing closing parentheses

- postmodern/prepare.lisp
- postmodern/tests/test-transactions.lisp
This fixes the problem identified in issue 357 that a prepared statement inside a transaction could try to drop a non-existent prepared statement, resulting in the entire transaction failing.
> Fix issue 357
