- cl-postgres/interpret.lisp
- cl-postgres/tests.lisp
I added support for binary reading of a bunch more array types and added tests for the various array types.
> Text array binary reader

- cl-postgres/interpret.lisp
- cl-postgres/tests.lisp
bytea (blobs), names, points, lsegs, boxes, varbits.
> More row type support

- cl-postgres/interpret.lisp
- cl-postgres/tests.lisp
This fixes retrieval of binary null arrays.
> Fix null arrays

- postmodern.asd
> Adding Sabra Crolleton as maintainer

- doc/postmodern.html
Following up on trying to  make the function naming scheme more consistent.
> Updated docs for schema-exists-p

- doc/s-sql.html
- s-sql/s-sql.lisp
Also fixed copy & paste error in create-database
> Add s-sql copy macro

- doc/postmodern.html
- postmodern/package.lisp
- postmodern/util.lisp
Cleaned up, documented and exported additional database inspection functions.
> Cleaned up, documented and exported additional database inspection functions.

- README.md
- doc/postmodern.html
- postmodern.asd
- postmodern/query.lisp
- postmodern/table.lisp
- postmodern/tests.lisp
- postmodern/util.lisp
- s-sql.asd
- s-sql/tests.lisp
Also some minor corrections in docs
> Resolve issue 134 regarding thread locks

- s-sql/s-sql.lisp
- Simplify STRCAT
- Use CHAR= to compare characters instead of EQ
> s-sql: Misc Changes

- ROADMAP.md
- doc/interval-notes.html
- doc/s-sql.html
- doc/simple-date.html
- postmodern.asd
- postmodern/query.lisp
- postmodern/transaction.lisp
- s-sql/s-sql.lisp
- s-sql/tests/test-intervals.lisp
> Corrected interval data type. More tests and documentation

- doc/array-notes.org
- doc/cl-postgres.org
- doc/dynamic-queries.org
- doc/index.org
- doc/interval-notes.org
- doc/postmodern.org
- doc/s-sql.org
- doc/simple-date.org
- postmodern/table.lisp
> Adding underlying org files to doc directory

- postmodern.asd
- postmodern/query.lisp
With the change testsuite says:
```lisp
Did 317 checks.
Pass: 314 (99%)
Skip: 0 ( 0%)
Fail: 3 ( 0%)
````
> Make it compilable by clasp, fix missing conditionalisation in query.lis

- doc/cl-postgres.html
- doc/cl-postgres.org
- doc/index.html
- doc/index.org
- doc/postmodern.html
- doc/postmodern.org
- doc/simple-date.org
- postmodern.asd
- postmodern/execute-file.lisp
- postmodern/tests/test-execute-file-broken-transaction.sql
- postmodern/tests/test-execute-file-broken.sql
- postmodern/tests/test-execute-file.lisp
- postmodern/tests/test-execute-file.sql
Adding documentation and tests for phoe's enhancement allowing postmodern to read and execute a file of sql statements.
Also has some clarification on the starting and stopping use of simple-date.
> Adding documentation and tests for phoe's enhancement allowing postmodern to read and execute a file of sql statements.

- cl-postgres/tests/test-package.lisp
- doc/postmodern.org
- postmodern/namespace.lisp
Implements proposal in #206. HTML changes not committed, as developer does not use emacs.
> Add :if-exists to drop-schema

- s-sql/s-sql.lisp
- s-sql/tests/test-tables.lisp
Same functionality as create-extended-table, so remove it.
> Remove s-sql op create-table-full

- postmodern/execute-file.lisp
> Fix empty queries in EXECUTE-FILE

- postmodern/execute-file.lisp
Fixes #222, ported over from https://github.com/dimitri/pgloader/pull/945
> Fix issue #945 from pgloader

- postmodern/util.lisp
I am an idiot. Thank you to Xach and Phoe.
> Delete duplicate functions

- doc/postmodern.html
- doc/postmodern.org
Cleaning up issue 242 re system breakage caused by deftype real
> Removed doc reference to real deftype

- doc/s-sql.html
- doc/s-sql.org
- postmodern/package.lisp
Also added some s-sql examples in the s-sql doc
> Export :db-null from Postmodern

- README.md
```diff
+ change code blocks to have syntax highlighting
+ Add spacing lines between horizontal rules and headings
- remove asterisks for list items and replace with dashes
+ fix formatting to satisfy markdown linter
```
> Markdown Formatting

- README.md
- doc/index.html
- doc/index.org
Just updating version number in some docs
> Updating version number in some docs

- CHANGELOG.md
- cl-postgres.asd
- cl-postgres/interpret.lisp
- cl-postgres/tests/test-binary-parameters.lisp
- cl-postgres/tests/tests.lisp
- doc/array-notes.html
- doc/array-notes.org
- postmodern.asd
- postmodern/tests/test-dao.lisp
- postmodern/tests/test-roles.lisp
- s-sql.asd
Selecting empty PG array produces NIL where it should be empty lisp array instead
> Fixing issue 311

- postmodern/prepare.lisp
When used with binary connections this macro generated code which calls the `find-postmodern-prepared-statement` function and when called in the second thread, this function returns `NIL`, because there is another connection in the `*database*` variable and it has empty `(postmodern::connection-meta *database*)` hash.
This fix makes prepared function ensure query is prepared in case if there is no information about it in the currently bound connection.
Also, this commit fixed the problem with `mismatched-parameter-types` condition which was signaled with unbound slots because it's initargs were specified as usual symbols instead of keywords.
> Fix macro postmodern:defprepared which wasn't threadsafe when used with binary connections

- s-sql/s-sql.lisp
- s-sql/tests/tests.lisp
I want to call analyze in my lisp code and I'd prefer to use s-sql as it keeps the name transformations etc consistent.
> Added postgres specific s-sql to postmodern.

- postmodern/package.lisp
Resolving issue 334. Exporting begin-transaction
> Export begin-transaction

- s-sql/s-sql.lisp
When doing a union over queries that use a with clause the with clauses aren't inside parens when they need to be for valid syntax.
e.g.
```common-lisp
(:union
(:with (:as 'cte1 (:parens (:select '* :from 'demo)))
(:select '*
:from 'base
:inner-join 'cte1
:on t))
(:with (:as 'cte2 (:parens (:select '* :from 'example)))
(:select '*
:from 'level
:left-join 'cte2
:on t))))
```
without this PR produces:
```SQL
(WITH cte1 AS  ((SELECT * FROM demo))
(SELECT *
FROM base 
INNER JOIN cte1 
ON true) 
union 
WITH cte2 AS  ((SELECT * FROM example))
(SELECT * 
FROM level 
LEFT JOIN cte2
ON true))
```
which fails.
with this PR it produces:
```SQL
(( WITH cte1 AS  ((SELECT * FROM demo))
(SELECT *
FROM base
INNER JOIN cte1
ON true) ) 
union
( WITH cte2 AS  ((SELECT * FROM example))
(SELECT *
FROM level …
```
> Updated :union & :union-all to wrap their subqueries in parens.

- s-sql/tests/tests.lisp
PR 338 added additional parentheses in certain s-sql cases involving union and union-all. This just updates the s-sql tests to take that into account.
> Updated tests for PR 338 on union, union-all

- s-sql/s-sql.lisp
- s-sql/tests/test-tables.lisp
Added create table as, allows you to copy tables with or without data and create tables as the result of a query.
> Added CREATE TABLE name AS ... to s-sql.
